### ISSUE TITLE
[Bug] GATT Server is disconnected

### ISSUE THREAD

**Issue by SpinCraft95** [pybricks/support#419] opened 2021-08-06 13:09 UTC
```
GATT Server is disconnected. Cannot retrieve services. (Re)connect first with `device.gatt.connect`.
```
Please i have this error can you help me ?

**Comment by dlech** [comment] 2021-08-06 13:59
Can you please give more details? What Operating System system and version do you use? What web browser and version do you use? What are the exact steps to reproduce the problem?

**Comment by SpinCraft95** [comment] 2021-08-06 14:03
I use windows 10 pro 20h2 and chrome 92 adn when i whant to connect the hub i do this :
-I click the green button and wiat the purple light
-i click on install pybrick firmware and select my technic hub
-it turn on green blue red and this error appeared

**Comment by dlech** [comment] 2021-08-06 18:07
Sounds like a duplicate of #312. If you have any more insights, please reply there.

Also see https://github.com/pybricks/support/discussions/270 for some troubleshooting tips.

**Closed by dlech** 2021-08-06 18:07 UTC
Labels: topic: bluetooth, software: pybricks-code
