### ISSUE TITLE
[Bug] DriveBase acting weird with high values?

### ISSUE THREAD

**Issue by Vinz1911** [pybricks/support#729] opened 2022-09-27 17:50 UTC
**Describe the bug**
I have a Spike prime with two large motors equipped. The DriveBase is starting acting weird after I set a high speed value or a high turn rate or both at the same time. For example: if I just add a speed value of 500 the robot accelerate very fast for a second and then drives slow ?!. If I add a high turn rate it's the same behavior, it starts turning fast for a second and then it drives/turns slow and sometimes it stops and starts turning in the wrong/opposite direction ?!. If I set a speed value of 300 and a turn rate of 45 (or values below) then everything seems to working correct.

As additional Question: If I set an acceleration value in the settings this does not affect the `drive()` method. it would be nice if I can also set the acceleration value as a setting for the `drive()` method. the default value is a bit slow for me.

**To reproduce**
This little Code snippet is enough to reproduce the behavior, sometimes it needs to restart a few times to trigger it.
```python
from pybricks.hubs import PrimeHub
from pybricks.pupdevices import Motor
from pybricks.parameters import Button, Color, Direction, Port, Stop
from pybricks.robotics import DriveBase
from pybricks.tools import wait, StopWatch

hub = PrimeHub()
left_motor = Motor(Port.A)
right_motor = Motor(Port.B, Direction.COUNTERCLOCKWISE)

base = DriveBase(left_motor, right_motor, 55, 125)

# high drive speed
base.drive(500, 45)

# or high turn rate or both
base.drive(500, 70)

while True: pass
```
**Expected behavior**
Drive as expected with high speed and correct turn rate

**Comment by laurensvalk** [comment] 2022-09-27 18:21
Thanks for reporting. Can you add the firmware version used for this experiment?

```python
from pybricks import version
print(version)
```

**Comment by Vinz1911** [comment] 2022-09-27 18:23
Yes sure:

```python
('primehub', '3.2.0b3', 'v3.2.0b3-67-gcaffa8a6 on 2022-09-14')
```

**Comment by laurensvalk** [comment] 2022-09-27 18:38
Could this be the same as #664 ?

I thought I had fixed it but apparently not.

**Comment by Vinz1911** [comment] 2022-09-27 18:44
So Problem also does NOT occur with the normal Spike Motors, I have it only with the Large ones.

It seems, this can be the Problem :D

**Comment by laurensvalk** [comment] 2022-09-29 14:38
I can reproduce this, but it is separate from #664.

In #664, there is strictly an issue about the pre-computed trajectory. The reference position jumps, but the PID controller still does as it's told: it goes to the bad trajectory.

But in this issue we have e.g:

```
motor.run(1000)
```
> then you also can reproduce it, it starts accelerating fast for a second and then keeps running on a much slower speed

So there is something wrong with the PID controller here.

**Comment by laurensvalk** [comment] 2022-09-29 14:54
Possibly the same cause. Run until stalled no longer works:

```python
from pybricks.pupdevices import Motor
from pybricks.parameters import Port

steer = Motor(Port.A)
left_end = steer.run_until_stalled(200)
```

**Comment by laurensvalk** [comment] 2022-10-04 13:53
![image](https://user-images.githubusercontent.com/12326241/193837946-916eb6b6-10d3-4ed9-ba32-87083e739e0b.png)

> So there is something wrong with the PID controller here.

The torque output is overflowing.

**Comment by laurensvalk** [comment] 2022-10-04 14:14
It looks much better after the fix :smile: 

![image](https://user-images.githubusercontent.com/12326241/193842964-398b8252-62f3-466f-8f13-8fc96dbf99e2.png)

**Comment by laurensvalk** [comment] 2022-10-04 14:56
[This build](https://github.com/pybricks/pybricks-micropython/actions/runs/3182851071) fixes the stall issue shown above.

It may or may not also fix the issue you saw.

**Comment by Vinz1911** [comment] 2022-10-04 15:14
This is absolutely Insane!!! 

Your fix work very well, it's like driving the robot on rails!
Also on high RPM no problems at all :)

**Comment by laurensvalk** [comment] 2022-10-04 17:03
Sounds like you’ve discovered the full potential of the recent drive base updates we’ve been working on 😄

**Comment by laurensvalk** [comment] 2022-10-04 18:43
Out of curiosity, since you’re the probably one of the first to try the new drive base, what is it that you like in particular? The new features or mainly the precision and performance?

**Comment by laurensvalk** [comment] 2022-10-18 13:41
Run until stalled is now fixed as well, so I think we can close this.

**Closed by laurensvalk** 2022-10-18 13:41 UTC
Labels: bug, topic: motors, software: pybricks-micropython
