### ISSUE TITLE
The hub took too long to respond. Restart the hub and try again.

### ISSUE THREAD

**Issue by ferhatozdmr** [pybricks/support#329] opened 2021-05-09 10:57 UTC
**Question**
I ghis error when I am trying to connect my movehub to macos 10.15.7

**Context**
What are you trying to accomplish that led to this question?

**Screenshots**
There is a saying that a picture is worth a 1000 words. Screenshots really help to identify and solve problems.

**Comment by ferhatozdmr** [comment] 2021-05-09 10:58
I have tried too many times. reinstalled original firmware and tried again. but I get the same error.

**Comment by dlech** [comment] 2021-05-09 14:15
Could you please try some of the things in our [Bluetooth Troubleshooting Guide](https://github.com/pybricks/support/discussions/270) to help us figure out what the problem is?

Which hub are you using?

**Comment by ferhatozdmr** [comment] 2021-05-09 15:59
Hi David, I couldn't get much info I guess. But here are some screenshots:
<img width="547" alt="Screen Shot 2021-05-09 at 18 49 57" src="https://user-images.githubusercontent.com/78050169/117578685-2be8ff00-b0f8-11eb-848f-668c7305a3c8.png">
<img width="772" alt="Screen Shot 2021-05-09 at 18 51 37" src="https://user-images.githubusercontent.com/78050169/117578690-30151c80-b0f8-11eb-839a-3001855d98a4.png">

I can control it with out any problems through https://legoboost.azurewebsites.net/ this web site. I know it uses totally different protocol but I believe this shows that there is no hardware or communication issue between the hub and my computer. In pybricks case, it finds my hub, starts flashing the drive only at the last step it gives this error.

**Comment by ferhatozdmr** [comment] 2021-05-10 16:41
I have installed the firmware on another windows machine, and now I connect it to my mac without ant issues. I don't know what the problem is installing firmware on a mac but if anybody has similar problem on mac, install the firmware on a windows pc and use your hub with your mac.

**Comment by dlech** [comment] 2021-05-10 16:49
If you are able to capture the Bluetooth packets on your Mac, it would be interesting to compare it to #256.

**Comment by dlech** [comment] 2021-05-17 19:28
We just released `pybricks-code@1.0.0-rc.2` that fixed #256. Could you try flashing the firmware on your Mac using this new version to see if the problem on Mac is fixed as well?

**Comment by ferhatozdmr** [comment] 2021-05-17 19:43
Hi David,

Unfortunately still the same problem. I get the same error.”The hub took to long to respond” as soon as the installation reaches to %100. 

I did not have any problem when I try to flash using windows pc though.

**Comment by dlech** [comment] 2021-05-17 19:50
Thanks for checking. If you have time, it would still be helpful to do a Bluetooth packet capture on the Mac. It would be nice if we could fix it in case other people have the same problem.

**Comment by ferhatozdmr** [comment] 2021-05-17 20:01
Hi David, 

I will try to do my best for packet capture but I am not familiar how exactly to do it. I tried to follow your documentation but when I run the capture it seems like it is capturing everything, I couldn’t seperate just the bluetooth that the hub is connected to. Or I am doing it completely wrong :) I will give it another try.

**Comment by dlech** [comment] 2021-05-17 20:11
It's been a while since I did that so I don't remember exactly where it is, but there are some filters in the PacketLogger.app that can be enabled to narrow it down to just Bluetooth traffic.

**Comment by ferhatozdmr** [comment] 2021-06-03 20:28
Hi David,

Is there any plans for enabling urandom for Movehub? or is there any other
alternative that I can use randint for movehub? I tried to search all the
documentation but I couldn't find any answer.

**Comment by dlech** [comment] 2021-06-03 20:33
I posted about this recently: https://github.com/pybricks/support/discussions/319

**Comment by ferhatozdmr** [comment] 2021-06-03 21:21
Oh sorry, I didn't see it :) . Thank you for your quick response David.

**Comment by ferhatozdmr** [comment] 2021-06-03 21:24
One more question, is there a way to use input function in pybricks? I am
trying to get an input from a user to make the robot move different ways.

**Comment by dlech** [comment] 2021-06-03 21:29
Yes, there are several issues and discussions covering this topic.

**Comment by ferhatozdmr** [comment] 2021-06-03 21:35
Thanks a lot, I'll check it out.

**Comment by laurensvalk** [comment] 2021-06-09 11:31
> I get the same error.”The hub took to long to respond” as soon as the installation reaches to %100.

I think I can reproduce this consistently on Android with the City Hub.

And I can add/confirm that the hub then goes back to blinking pink, so there's no firmware on the hub; it's not just a matter of restarting the hub.

If this is not reproducable for you @dlech, I'll try to find logs as needed.

**Comment by dlech** [comment] 2021-06-09 13:32
I would rather start a new issue about Android since this one is about macOS.

**Comment by laurensvalk** [comment] 2021-06-09 14:49
It was more to confirm that it can in fact get to 100% and still be without a valid firmware, which we weren't sure about yet in a recent discussion.

**Comment by laurensvalk** [comment] 2022-11-02 09:02
On the Move Hub specifically, fresh batteries seem to make a big difference as well.

**Comment by dlech** [comment] 2023-03-20 21:59
Closing since Pybricks Code and the firmware has changed significantly since the initial report, so any reports of the same error message are not necessarily the same issue.

If anyone who has a problem that is fixed by turning off other Bluetooth devices, please capture Bluetooth logs as described [here](https://bleak.readthedocs.io/en/latest/troubleshooting.html#macos) and post the results in #938. This seems to b a common problem and could help other users if we can understand it better.

**Closed by dlech** 2023-03-20 21:59 UTC
Labels: bug, hub: movehub, topic: bluetooth, OS: macOS, software: pybricks-code
