### ISSUE TITLE
[Question] "Can't import name Remote"

### ISSUE THREAD

**Issue by piotrmil** [pybricks/support#481] opened 2021-09-15 17:49 UTC
I was really excited to try this. I bootloaded the program onto my Technic hub, copied the defeault program, clicked the play button, and....

error. 

Apparently on line 1. Can't import name Remote.

So, wtf?

**Comment by laurensvalk** [comment] 2021-09-15 18:11
The remote feature is still in beta. It looks like you are using the stable version, which does not have the remote yet.

If you install the firmware and run the program with this version, it should work:

https://beta.pybricks.com/

**Comment by piotrmil** [comment] 2021-09-15 18:13
Cool. I'd suggest adding that to the error code to avoid confusion.

**Comment by piotrmil** [comment] 2021-09-15 18:19
Wait, I AM using beta. what is going on?!

**Comment by laurensvalk** [comment] 2021-09-15 18:20
```python
from pybricks import version
print(version)
```

What is the output if you run this?

**Comment by piotrmil** [comment] 2021-09-15 18:32
technichub 3.0.0 8845360 on 2021-06-09

**Comment by laurensvalk** [comment] 2021-09-15 18:33
Is that all the output you see? Could you try a screenshot instead? It seems as if a few characters are missing.

**Comment by piotrmil** [comment] 2021-09-15 18:35
I'm using it on a different computer, I have to go back and forth, what AM I missing apparently?

**Comment by dlech** [comment] 2021-09-15 18:35
> 2021-06-09

This is not the latest firmware. Please update the firmware using the firmware update button on https://beta.pybricks.com.

**Comment by piotrmil** [comment] 2021-09-15 18:38
I clicked "check for update" and it says that it is up to date. Yes, I am on the beta. page.

**Comment by dlech** [comment] 2021-09-15 18:39
![image](https://user-images.githubusercontent.com/963645/133490633-f9a056df-2bed-4057-8669-1f8495e5a39a.png)

this button

**Comment by laurensvalk** [comment] 2021-09-15 18:40
But you might have installed the firmware on the hub using the older version.

We probably have to add an indication that a firmware update is required.

**Comment by dlech** [comment] 2021-09-15 18:41
> We probably have to add an indication that a firmware update is required.

pretty sure we already have this

**Comment by laurensvalk** [comment] 2021-09-15 18:41
I'll give it a try. It seems like this question about the remote has come up a lot.

**Comment by piotrmil** [comment] 2021-09-15 18:43
The Firmware button is greyed out when I pair the device. Can't click it.

**Comment by piotrmil** [comment] 2021-09-15 18:44
> 
> 
> But you might have installed the firmware on the hub using the older version.
> 
> We probably have to add an indication that a firmware update is required.

Yeah, that sounds sensible I'd say.

**Comment by laurensvalk** [comment] 2021-09-15 18:45
You install the new firmware in the same way you did it before.

That is, turn the hub off. Then press and hold the button until it blinks purple. Then click the installation button.

**Comment by dlech** [comment] 2021-09-15 18:46
there are instructions and a video here: https://pybricks.com/install/technic-boost-city/

**Comment by dlech** [comment] 2021-09-15 18:50
> I'll give it a try. It seems like this question about the remote has come up a lot.

This is the expected message: https://github.com/pybricks/pybricks-code/blob/094807ccb513b3bb1908b95bc45214e3bb0557a8/src/notifications/i18n.en.json#L9

This message also happens in response to BlueZ bugs. So we could probably add a better version check and message.

**Comment by piotrmil** [comment] 2021-09-15 18:54
Okay, now it works like a charm :) version 3.1.0a4 from 2021-08-30.

Thanks! I would suggest expanding error messages to give some instructions to avoid giving you guys more work here ;) Especially now since RacingBricks made a video about you.

**Comment by dlech** [comment] 2021-09-15 19:02
What OS are you using Pybricks Code on?

**Comment by dlech** [comment] 2021-09-15 19:30
We started a new issue for the informational message, so closing this issue since the problem is resolved.

**Closed by dlech** 2021-09-15 19:30 UTC
Labels: triage
