### ISSUE TITLE
[Feature] Enable ev3 hub to set led0 and led1 separately

### ISSUE THREAD

**Issue by BertLindeman** [pybricks/support#98] opened 2020-07-15 16:03 UTC
**Is your feature request related to a problem? Please describe.**
The EV3 hub has two leds (led0 and led1 in the /sys/class/leds directory).
The current implementation only sets **both** leds 

**Describe the solution you'd like**
I would like to be able to set led0 and led1 seperately. 
So e.g. I could indicate chosen direction of the robot by setting the led.

**Describe alternatives you've considered**
Only both leds can be set at the moment

**Additional context**
None

**Comment by BertLindeman** [comment] 2020-07-15 16:04
To be sure: this is a low priority  request!

**Comment by dlech** [comment] 2020-07-18 00:51
Duplicate of #67

**Closed by dlech** 2020-07-18 00:51 UTC
Labels: duplicate, enhancement, platform: EV3
